/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'surface': '#faf8ff',
        'on-surface': '#131b2e',
        'on-surface-variant': '#434655',
        'surface-dim': '#d2d9f4',
        'surface-bright': '#faf8ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f3ff',
        'surface-container': '#eaedff',
        'surface-container-high': '#e2e7ff',
        'surface-container-highest': '#dae2fd',
        'primary': '#004ac6',
        'on-primary': '#ffffff',
        'primary-container': '#2563eb',
        'on-primary-container': '#eeefff',
        'primary-fixed': '#dbe1ff',
        'primary-fixed-dim': '#b4c5ff',
        'on-primary-fixed': '#00174b',
        'on-primary-fixed-variant': '#003ea8',
        'secondary': '#006c4a',
        'on-secondary': '#ffffff',
        'secondary-container': '#82f5c1',
        'on-secondary-container': '#00714e',
        'secondary-fixed': '#85f8c4',
        'secondary-fixed-dim': '#68dba9',
        'on-secondary-fixed': '#002114',
        'on-secondary-fixed-variant': '#005137',
        'tertiary': '#005a89',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#0073ae',
        'on-tertiary-container': '#e7f2ff',
        'tertiary-fixed': '#cce5ff',
        'tertiary-fixed-dim': '#93ccff',
        'on-tertiary-fixed': '#001d31',
        'on-tertiary-fixed-variant': '#004b73',
        'outline': '#737686',
        'outline-variant': '#c3c6d7',
        'inverse-surface': '#283044',
        'inverse-on-surface': '#eef0ff',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        heading: ['Space Grotesk', 'Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      boxShadow: {
        'soft-card': '0 4px 20px -2px rgba(15, 23, 42, 0.05)',
        'soft-card-hover': '0 10px 25px -3px rgba(15, 23, 42, 0.08)',
        'glow-blue': '0 0 0 3px rgba(37, 99, 235, 0.15)',
      }
    },
  },
  plugins: [],
}
